version: '3.3'

services:
  pb-nginx.docker:
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx/sites:/etc/nginx/conf.d

  pb-app.docker:
    volumes:
      - ./app:/var/www/app
      - ./app/php.ini-development:/usr/local/etc/php/php.ini
      - ./app/policy.xml:/etc/ImageMagick-6/policy.xml

  pb-app-queue.docker:
    volumes:
      - ./app:/var/www/app
      - ./app/php.ini-development:/usr/local/etc/php/php.ini
      - ./app/policy.xml:/etc/ImageMagick-6/policy.xml

  pb-app-scheduler.docker:
    volumes:
      - ./app:/var/www/app
      - ./app/php.ini-development:/usr/local/etc/php/php.ini
      - ./app/policy.xml:/etc/ImageMagick-6/policy.xml

  pb-mysql.docker:
    image: mysql:5.7
    container_name: pb-mysql
    environment:
      MYSQL_DATABASE: 'photo_blog'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'dev'
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/seed:/docker-entrypoint-initdb.d
      - ./docker/mysql/storage:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

  pb-maildev.docker:
    image: djfarrelly/maildev
    container_name: pb-maildev
    ports:
      - 8083:80